// lib/monsters.ts

export type Rarity = 'COMMON' | 'RARE' | 'LEGENDARY';

export interface Monster {
  id: string;
  name: string;
  emoji: string; // 타입 이모지 (예: 🔥, 💧, ⚡)
  rarity: Rarity;
  description: string;
}

// 타입별 이모지 매핑 (참고용)
// 풀:🌿 불:🔥 물:💧 전기:⚡ 얼음:❄️ 격투:👊 독:☠️ 땅:🏜️
// 비행:🕊️ 에스퍼:🔮 벌레:🐛 바위:🪨 고스트:👻 드래곤:🐲 강철:⚙️ 페어리:✨ 노말:⚪

export const MONSTER_LIST: Monster[] = [
  // ==========================================
  // 🌱 COMMON (흔함) - 약 60% 확률
  // ==========================================
  { id: 'c1', name: '이상해씨', emoji: '🌿', rarity: 'COMMON', description: '등의 씨앗에서 꽃이 핍니다.' },
  { id: 'c2', name: '캐터피', emoji: '🐛', rarity: 'COMMON', description: '초록색 껍질로 덮여 있습니다.' },
  { id: 'c3', name: '뿔충이', emoji: '🐛', rarity: 'COMMON', description: '머리에 날카로운 침이 있습니다.' },
  { id: 'c4', name: '구구', emoji: '🕊️', rarity: 'COMMON', description: '가장 흔하게 볼 수 있는 새입니다.' },
  { id: 'c5', name: '꼬렛', emoji: '⚪', rarity: 'COMMON', description: '어디든지 나타나는 쥐입니다.' },
  { id: 'c6', name: '깨비참', emoji: '🕊️', rarity: 'COMMON', description: '성격이 급하고 사납습니다.' },
  { id: 'c7', name: '아보', emoji: '☠️', rarity: 'COMMON', description: '소리 없이 먹이 뒤를 쫓습니다.' },
  { id: 'c8', name: '모래두지', emoji: '🏜️', rarity: 'COMMON', description: '마른 모래 땅을 좋아합니다.' },
  { id: 'c9', name: '니드런♀', emoji: '☠️', rarity: 'COMMON', description: '작지만 독침을 가지고 있습니다.' },
  { id: 'c10', name: '니드런♂', emoji: '☠️', rarity: 'COMMON', description: '귀를 움직여 주위를 경계합니다.' },
  { id: 'c11', name: '삐삐', emoji: '✨', rarity: 'COMMON', description: '달빛을 모아서 공중에 뜹니다.' },
  { id: 'c12', name: '식스테일', emoji: '🔥', rarity: 'COMMON', description: '불꽃을 조종하는 여우입니다.' },
  { id: 'c13', name: '푸린', emoji: '⚪', rarity: 'COMMON', description: '노래를 부르면 모두 잠이 듭니다.' },
  { id: 'c14', name: '주뱃', emoji: '☠️', rarity: 'COMMON', description: '동굴에 사는 박쥐입니다.' },
  { id: 'c15', name: '뚜벅쵸', emoji: '🌿', rarity: 'COMMON', description: '밤이 되면 활동을 시작합니다.' },
  { id: 'c16', name: '파라스', emoji: '🐛', rarity: 'COMMON', description: '등에 버섯이 자라고 있습니다.' },
  { id: 'c17', name: '콘팡', emoji: '🐛', rarity: 'COMMON', description: '밤에 불빛을 찾아다닙니다.' },
  { id: 'c18', name: '디그다', emoji: '🏜️', rarity: 'COMMON', description: '땅속을 파고 돌아다닙니다.' },
  { id: 'c19', name: '나옹', emoji: '⚪', rarity: 'COMMON', description: '반짝이는 것을 좋아합니다.' },
  { id: 'c20', name: '고라파덕', emoji: '💧', rarity: 'COMMON', description: '항상 두통에 시달립니다.' },
  { id: 'c21', name: '망키', emoji: '👊', rarity: 'COMMON', description: '화를 잘 내는 성격입니다.' },
  { id: 'c22', name: '가디', emoji: '🔥', rarity: 'COMMON', description: '주인을 잘 따르는 강아지입니다.' },
  { id: 'c23', name: '발챙이', emoji: '💧', rarity: 'COMMON', description: '배에 소용돌이 무늬가 있습니다.' },
  { id: 'c24', name: '캐이시', emoji: '🔮', rarity: 'COMMON', description: '잠만 자지만 초능력을 씁니다.' },
  { id: 'c25', name: '알통몬', emoji: '👊', rarity: 'COMMON', description: '운동을 좋아하는 포켓몬입니다.' },
  { id: 'c26', name: '모다피', emoji: '🌿', rarity: 'COMMON', description: '가늘고 유연한 몸을 가졌습니다.' },
  { id: 'c27', name: '왕눈해', emoji: '💧', rarity: 'COMMON', description: '바다를 떠다니는 해파리입니다.' },
  { id: 'c28', name: '꼬마돌', emoji: '🪨', rarity: 'COMMON', description: '돌맹이처럼 생겼습니다.' },
  { id: 'c29', name: '포니타', emoji: '🔥', rarity: 'COMMON', description: '불꽃 갈기를 가진 말입니다.' },
  { id: 'c30', name: '야돈', emoji: '💧', rarity: 'COMMON', description: '항상 멍하니 있습니다.' },
  { id: 'c31', name: '코일', emoji: '⚡', rarity: 'COMMON', description: '자석으로 공중에 떠 있습니다.' },
  { id: 'c32', name: '파오리', emoji: '⚪', rarity: 'COMMON', description: '파를 들고 다닙니다.' },
  { id: 'c33', name: '두두', emoji: '⚪', rarity: 'COMMON', description: '머리가 두 개 달린 새입니다.' },
  { id: 'c34', name: '쥬쥬', emoji: '💧', rarity: 'COMMON', description: '추운 바다를 좋아합니다.' },
  { id: 'c35', name: '질퍽이', emoji: '☠️', rarity: 'COMMON', description: '더러운 진흙에서 태어났습니다.' },
  { id: 'c36', name: '셀러', emoji: '💧', rarity: 'COMMON', description: '단단한 껍질로 몸을 지킵니다.' },
  { id: 'c37', name: '고오스', emoji: '👻', rarity: 'COMMON', description: '가스로 이루어진 몸입니다.' },
  { id: 'c38', name: '롱스톤', emoji: '🪨', rarity: 'COMMON', description: '거대한 돌 뱀입니다.' },
  { id: 'c39', name: '슬리프', emoji: '🔮', rarity: 'COMMON', description: '꿈을 먹는 포켓몬입니다.' },
  { id: 'c40', name: '크랩', emoji: '💧', rarity: 'COMMON', description: '집게발이 강력합니다.' },
  { id: 'c41', name: '찌리리공', emoji: '⚡', rarity: 'COMMON', description: '몬스터볼과 비슷하게 생겼습니다.' },
  { id: 'c42', name: '아라리', emoji: '🔮', rarity: 'COMMON', description: '알들이 모여 있습니다.' },
  { id: 'c43', name: '탕구리', emoji: '🏜️', rarity: 'COMMON', description: '뼈다귀를 들고 다닙니다.' },
  { id: 'c44', name: '또가스', emoji: '☠️', rarity: 'COMMON', description: '독가스를 뿜어냅니다.' },
  { id: 'c45', name: '뿔카노', emoji: '🏜️', rarity: 'COMMON', description: '피부가 갑옷처럼 단단합니다.' },
  { id: 'c46', name: '쏘드라', emoji: '💧', rarity: 'COMMON', description: '위험하면 먹물을 뿜습니다.' },
  { id: 'c47', name: '콘치', emoji: '💧', rarity: 'COMMON', description: '우아하게 헤엄칩니다.' },
  { id: 'c48', name: '별가사', emoji: '💧', rarity: 'COMMON', description: '별 모양의 포켓몬입니다.' },
  { id: 'c49', name: '잉어킹', emoji: '💧', rarity: 'COMMON', description: '세상에서 제일 약한 포켓몬?' },
  { id: 'c50', name: '메타몽', emoji: '⚪', rarity: 'COMMON', description: '무엇으로든 변신할 수 있습니다.' },
  { id: 'c51', name: '치코리타', emoji: '🌿', rarity: 'COMMON', description: '머리의 잎사귀가 특징입니다.' },
  { id: 'c52', name: '브케인', emoji: '🔥', rarity: 'COMMON', description: '등에서 불꽃을 뿜습니다.' },
  { id: 'c53', name: '리아코', emoji: '💧', rarity: 'COMMON', description: '무엇이든 물어버립니다.' },
  { id: 'c54', name: '꼬리선', emoji: '⚪', rarity: 'COMMON', description: '꼬리로 서서 망을 봅니다.' },
  { id: 'c55', name: '부우부', emoji: '⚪', rarity: 'COMMON', description: '정확한 시간을 알려줍니다.' },
  { id: 'c56', name: '레디바', emoji: '🐛', rarity: 'COMMON', description: '별빛을 에너지로 삼습니다.' },
  { id: 'c57', name: '페이검', emoji: '🐛', rarity: 'COMMON', description: '거미줄을 칩니다.' },
  { id: 'c58', name: '초라기', emoji: '💧', rarity: 'COMMON', description: '더듬이에서 빛을 냅니다.' },
  { id: 'c59', name: '피츄', emoji: '⚡', rarity: 'COMMON', description: '아직 전기를 잘 다루지 못해요.' },
  { id: 'c60', name: '토게피', emoji: '✨', rarity: 'COMMON', description: '행운을 가져다줍니다.' },
  { id: 'c61', name: '메리프', emoji: '⚡', rarity: 'COMMON', description: '털에서 정전기가 일어납니다.' },
  { id: 'c62', name: '마릴', emoji: '💧', rarity: 'COMMON', description: '물에 뜨는 꼬리를 가졌습니다.' },
  { id: 'c63', name: '꼬지모', emoji: '🪨', rarity: 'COMMON', description: '나무인 척 하는 바위 포켓몬.' },
  { id: 'c64', name: '통통코', emoji: '🌿', rarity: 'COMMON', description: '바람에 날려다닙니다.' },
  { id: 'c65', name: '에이팜', emoji: '⚪', rarity: 'COMMON', description: '꼬리를 손처럼 씁니다.' },
  { id: 'c66', name: '해너츠', emoji: '🌿', rarity: 'COMMON', description: '영양분을 모으고 있습니다.' },
  { id: 'c67', name: '왕자리', emoji: '🐛', rarity: 'COMMON', description: '눈이 커서 잘 봅니다.' },
  { id: 'c68', name: '우퍼', emoji: '💧', rarity: 'COMMON', description: '물과 땅을 오갑니다.' },
  { id: 'c69', name: '니로우', emoji: '🌑', rarity: 'COMMON', description: '불행을 가져온다고 믿어졌습니다.' },
  { id: 'c70', name: '무우마', emoji: '👻', rarity: 'COMMON', description: '장난을 좋아하는 유령입니다.' },
  { id: 'c71', name: '안농', emoji: '🔮', rarity: 'COMMON', description: '고대 문자를 닮았습니다.' },
  { id: 'c72', name: '마자용', emoji: '🔮', rarity: 'COMMON', description: '참기 포켓몬입니다.' },
  { id: 'c73', name: '키링키', emoji: '⚪', rarity: 'COMMON', description: '꼬리에도 뇌가 있습니다.' },
  { id: 'c74', name: '피콘', emoji: '🐛', rarity: 'COMMON', description: '솔방울처럼 생겼습니다.' },
  { id: 'c75', name: '노고치', emoji: '⚪', rarity: 'COMMON', description: '땅굴을 파고 숨습니다.' },
  { id: 'c76', name: '글라이거', emoji: '🏜️', rarity: 'COMMON', description: '소리 없이 활강합니다.' },
  { id: 'c77', name: '블루', emoji: '✨', rarity: 'COMMON', description: '무서운 얼굴이지만 겁이 많아요.' },
  { id: 'c78', name: '침바루', emoji: '💧', rarity: 'COMMON', description: '몸을 부풀려 가시를 세웁니다.' },
  { id: 'c79', name: '단단지', emoji: '🐛', rarity: 'COMMON', description: '나무열매를 발효시킵니다.' },
  { id: 'c80', name: '헤라크로스', emoji: '🐛', rarity: 'COMMON', description: '힘이 장사입니다.' },
  { id: 'c81', name: '포푸니', emoji: '🌑', rarity: 'COMMON', description: '날카로운 손톱을 가졌습니다.' },
  { id: 'c82', name: '깜지곰', emoji: '⚪', rarity: 'COMMON', description: '달콤한 꿀을 좋아합니다.' },
  { id: 'c83', name: '마그마그', emoji: '🔥', rarity: 'COMMON', description: '몸이 용암으로 되어 있습니다.' },
  { id: 'c84', name: '꾸꾸리', emoji: '❄️', rarity: 'COMMON', description: '냄새를 잘 맡습니다.' },
  { id: 'c85', name: '코산호', emoji: '💧', rarity: 'COMMON', description: '아름다운 산호초입니다.' },
  { id: 'c86', name: '총어', emoji: '💧', rarity: 'COMMON', description: '물의 분사해 공격합니다.' },
  { id: 'c87', name: '딜리버드', emoji: '❄️', rarity: 'COMMON', description: '선물을 배달합니다.' },
  { id: 'c88', name: '만타인', emoji: '💧', rarity: 'COMMON', description: '우아하게 헤엄칩니다.' },
  { id: 'c89', name: '무장조', emoji: '⚙️', rarity: 'COMMON', description: '강철 깃털을 가졌습니다.' },
  { id: 'c90', name: '델빌', emoji: '🌑', rarity: 'COMMON', description: '동료와 협동하여 사냥합니다.' },
  { id: 'c91', name: '코코리', emoji: '🏜️', rarity: 'COMMON', description: '긴 코로 물을 뿜습니다.' },
  { id: 'c92', name: '노라키', emoji: '⚪', rarity: 'COMMON', description: '뿔의 모양이 신기합니다.' },
  { id: 'c93', name: '루브도', emoji: '⚪', rarity: 'COMMON', description: '꼬리로 그림을 그립니다.' },
  { id: 'c94', name: '배루키', emoji: '👊', rarity: 'COMMON', description: '항상 싸울 상대를 찾습니다.' },
  { id: 'c95', name: '뽀뽀라', emoji: '❄️', rarity: 'COMMON', description: '입술이 민감합니다.' },
  { id: 'c96', name: '에레키드', emoji: '⚡', rarity: 'COMMON', description: '팔을 돌려 전기를 만듭니다.' },
  { id: 'c97', name: '마그비', emoji: '🔥', rarity: 'COMMON', description: '입에서 불똥이 튑니다.' },
  { id: 'c98', name: '밀탱크', emoji: '⚪', rarity: 'COMMON', description: '맛있는 우유를 만듭니다.' },
  { id: 'c99', name: '에버라스', emoji: '🪨', rarity: 'COMMON', description: '흙을 먹으며 자랍니다.' },
  { id: 'c100', name: '나무지기', emoji: '🌿', rarity: 'COMMON', description: '숲의 나무를 잘 탑니다.' },

  // ==========================================
  // ✨ RARE (희귀) - 약 35% 확률
  // ==========================================
  { id: 'r1', name: '피카츄', emoji: '⚡', rarity: 'RARE', description: '전기를 뿜는 귀여운 쥐!' },
  { id: 'r2', name: '라이츄', emoji: '⚡', rarity: 'RARE', description: '전기가 꼬리에 모입니다.' },
  { id: 'r3', name: '파이리', emoji: '🔥', rarity: 'RARE', description: '꼬리의 불이 생명입니다.' },
  { id: 'r4', name: '리자드', emoji: '🔥', rarity: 'RARE', description: '성격이 거친 불꽃 포켓몬.' },
  { id: 'r5', name: '리자몽', emoji: '🔥', rarity: 'RARE', description: '용과 같은 강력한 날개!' },
  { id: 'r6', name: '꼬부기', emoji: '💧', rarity: 'RARE', description: '단단한 등껍질로 방어합니다.' },
  { id: 'r7', name: '어니부기', emoji: '💧', rarity: 'RARE', description: '털이 덮인 꼬리가 특징.' },
  { id: 'r8', name: '거북왕', emoji: '💧', rarity: 'RARE', description: '등의 대포로 물을 발사!' },
  { id: 'r9', name: '이상해풀', emoji: '🌿', rarity: 'RARE', description: '꽃봉오리가 자라났습니다.' },
  { id: 'r10', name: '이상해꽃', emoji: '🌿', rarity: 'RARE', description: '거대한 꽃에서 향기가 납니다.' },
  { id: 'r11', name: '버터플', emoji: '🐛', rarity: 'RARE', description: '아름다운 날개를 가졌습니다.' },
  { id: 'r12', name: '독침붕', emoji: '🐝', rarity: 'RARE', description: '강력한 독침을 조심하세요.' },
  { id: 'r13', name: '피죤투', emoji: '🕊️', rarity: 'RARE', description: '마하의 속도로 비행합니다.' },
  { id: 'r14', name: '나인테일', emoji: '🔥', rarity: 'RARE', description: '9개의 꼬리를 가진 신비한 포켓몬.' },
  { id: 'r15', name: '윈디', emoji: '🔥', rarity: 'RARE', description: '전설처럼 전해지는 포켓몬.' },
  { id: 'r16', name: '후딘', emoji: '🔮', rarity: 'RARE', description: 'IQ 5000의 천재 포켓몬.' },
  { id: 'r17', name: '괴력몬', emoji: '👊', rarity: 'RARE', description: '4개의 팔로 무엇이든 던집니다.' },
  { id: 'r18', name: '딱구리', emoji: '🪨', rarity: 'RARE', description: '폭탄처럼 굴러다닙니다.' },
  { id: 'r19', name: '팬텀', emoji: '👻', rarity: 'RARE', description: '그림자 속에 숨어 있습니다.' },
  { id: 'r20', name: '롱스톤', emoji: '🪨', rarity: 'RARE', description: '거대한 바위 뱀.' },
  { id: 'r21', name: '텅구리', emoji: '🏜️', rarity: 'RARE', description: '뼈를 부메랑처럼 씁니다.' },
  { id: 'r22', name: '럭키', emoji: '⚪', rarity: 'RARE', description: '행운을 가져다주는 포켓몬.' },
  { id: 'r23', name: '갸라도스', emoji: '💧', rarity: 'RARE', description: '폭포를 오르는 용.' },
  { id: 'r24', name: '라프라스', emoji: '❄️', rarity: 'RARE', description: '사람을 태우고 바다를 건넙니다.' },
  { id: 'r25', name: '메타몽', emoji: '✨', rarity: 'RARE', description: '변신의 귀재!' },
  { id: 'r26', name: '이브이', emoji: '⚪', rarity: 'RARE', description: '다양한 진화의 가능성.' },
  { id: 'r27', name: '샤미드', emoji: '💧', rarity: 'RARE', description: '물에 녹아들 수 있습니다.' },
  { id: 'r28', name: '쥬피썬더', emoji: '⚡', rarity: 'RARE', description: '털이 바늘처럼 곤두섭니다.' },
  { id: 'r29', name: '부스터', emoji: '🔥', rarity: 'RARE', description: '체온이 매우 높습니다.' },
  { id: 'r30', name: '폴리곤', emoji: '⚙️', rarity: 'RARE', description: '인공적으로 만들어진 포켓몬.' },
  { id: 'r31', name: '잠만보', emoji: '⚪', rarity: 'RARE', description: '먹고 자는 것이 일상입니다.' },
  { id: 'r32', name: '미뇽', emoji: '🐲', rarity: 'RARE', description: '환상의 포켓몬이라 불렸습니다.' },
  { id: 'r33', name: '신뇽', emoji: '🐲', rarity: 'RARE', description: '날씨를 조종한다고 합니다.' },
  { id: 'r34', name: '망나뇽', emoji: '🐲', rarity: 'RARE', description: '바다의 화신, 따뜻한 마음씨.' },
  { id: 'r35', name: '메가니움', emoji: '🌿', rarity: 'RARE', description: '숨결이 시든 풀을 살립니다.' },
  { id: 'r36', name: '블레이범', emoji: '🔥', rarity: 'RARE', description: '폭발적인 불꽃을 뿜습니다.' },
  { id: 'r37', name: '장크로다일', emoji: '💧', rarity: 'RARE', description: '거대한 턱 힘을 자랑합니다.' },
  { id: 'r38', name: '전룡', emoji: '⚡', rarity: 'RARE', description: '꼬리의 빛이 등대 역할을 합니다.' },
  { id: 'r39', name: '마릴리', emoji: '💧', rarity: 'RARE', description: '물속에서 숨을 잘 쉽니다.' },
  { id: 'r40', name: '에브이', emoji: '🔮', rarity: 'RARE', description: '주인을 지키기 위해 예지력을 씁니다.' },
  { id: 'r41', name: '블래키', emoji: '🌑', rarity: 'RARE', description: '달빛을 받으면 무늬가 빛납니다.' },
  { id: 'r42', name: '강철톤', emoji: '⚙️', rarity: 'RARE', description: '다이아몬드보다 단단한 몸.' },
  { id: 'r43', name: '핫삼', emoji: '🐛', rarity: 'RARE', description: '강철 집게로 적을 부숩니다.' },
  { id: 'r44', name: '헤라크로스', emoji: '🐛', rarity: 'RARE', description: '꿀을 좋아하는 장사.' },
  { id: 'r45', name: '링곰', emoji: '⚪', rarity: 'RARE', description: '숲의 난폭자.' },
  { id: 'r46', name: '무장조', emoji: '⚙️', rarity: 'RARE', description: '갑옷 새 포켓몬.' },
  { id: 'r47', name: '헬가', emoji: '🌑', rarity: 'RARE', description: '지옥의 개라 불립니다.' },
  { id: 'r48', name: '킹드라', emoji: '🐲', rarity: 'RARE', description: '깊은 바다의 주인.' },
  { id: 'r49', name: '해피너스', emoji: '⚪', rarity: 'RARE', description: '행복을 나눠주는 간호사.' },
  { id: 'r50', name: '마기라스', emoji: '🪨', rarity: 'RARE', description: '산을 부수는 힘을 가졌습니다.' },
  { id: 'r51', name: '나무킹', emoji: '🌿', rarity: 'RARE', description: '숲속의 민첩한 전사.' },
  { id: 'r52', name: '번치코', emoji: '🔥', rarity: 'RARE', description: '불꽃 킥을 날립니다.' },
  { id: 'r53', name: '대짱이', emoji: '💧', rarity: 'RARE', description: '바위를 끄는 괴력.' },
  { id: 'r54', name: '가디안', emoji: '🔮', rarity: 'RARE', description: '미래를 예지하는 포켓몬.' },
  { id: 'r55', name: '보스로라', emoji: '⚙️', rarity: 'RARE', description: '철의 영역을 지킵니다.' },
  { id: 'r56', name: '플라이곤', emoji: '🐲', rarity: 'RARE', description: '사막의 정령.' },
  { id: 'r57', name: '파비코리', emoji: '🐲', rarity: 'RARE', description: '구름 같은 날개.' },
  { id: 'r58', name: '밀로틱', emoji: '💧', rarity: 'RARE', description: '세상에서 가장 아름다운 포켓몬.' },
  { id: 'r59', name: '보만다', emoji: '🐲', rarity: 'RARE', description: '하늘을 나는 꿈을 이룬 용.' },
  { id: 'r60', name: '메타그ロス', emoji: '⚙️', rarity: 'RARE', description: '4개의 뇌를 가진 슈퍼컴퓨터.' },
  { id: 'r61', name: '루카리오', emoji: '👊', rarity: 'RARE', description: '파동을 읽는 전사.' },
  { id: 'r62', name: '한카리아스', emoji: '🐲', rarity: 'RARE', description: '소리보다 빠르게 비행합니다.' },
  { id: 'r63', name: '토게키스', emoji: '✨', rarity: 'RARE', description: '축복을 내려주는 포켓몬.' },
  { id: 'r64', name: '리피아', emoji: '🌿', rarity: 'RARE', description: '광합성을 하는 이브이 진화형.' },
  { id: 'r65', name: '글레이시아', emoji: '❄️', rarity: 'RARE', description: '눈보라를 일으키는 이브이 진화형.' },
  { id: 'r66', name: '개굴닌자', emoji: '💧', rarity: 'RARE', description: '물로 된 수리검을 던집니다.' },
  { id: 'r67', name: '님피아', emoji: '✨', rarity: 'RARE', description: '리본으로 마음을 전합니다.' },
  { id: 'r68', name: '따라큐', emoji: '👻', rarity: 'RARE', description: '피카츄 탈을 쓴 외로운 포켓몬.' },
  { id: 'r69', name: '드래펄트', emoji: '🐲', rarity: 'RARE', description: '머리에 드라꼰을 태우고 다닙니다.' },
  { id: 'r70', name: '두드리짱', emoji: '✨', rarity: 'RARE', description: '거대한 망치를 휘두릅니다.' },

  // ==========================================
  // 👑 LEGENDARY (전설) - 약 5% 확률
  // ==========================================
  { id: 'l1', name: '프리져', emoji: '❄️', rarity: 'LEGENDARY', description: '전설의 얼음 새 포켓몬.' },
  { id: 'l2', name: '썬더', emoji: '⚡', rarity: 'LEGENDARY', description: '전설의 전기 새 포켓몬.' },
  { id: 'l3', name: '파이어', emoji: '🔥', rarity: 'LEGENDARY', description: '전설의 불꽃 새 포켓몬.' },
  { id: 'l4', name: '뮤츠', emoji: '🔮', rarity: 'LEGENDARY', description: '최강을 위해 만들어진 포켓몬.' },
  { id: 'l5', name: '뮤', emoji: '🔮', rarity: 'LEGENDARY', description: '모든 포켓몬의 유전자를 가졌습니다.' },
  { id: 'l6', name: '라이코', emoji: '⚡', rarity: 'LEGENDARY', description: '번개와 함께 달리는 전설.' },
  { id: 'l7', name: '앤테이', emoji: '🔥', rarity: 'LEGENDARY', description: '화산의 분화를 짖는 전설.' },
  { id: 'l8', name: '스이쿤', emoji: '💧', rarity: 'LEGENDARY', description: '더러운 물을 정화하는 전설.' },
  { id: 'l9', name: '루기아', emoji: '🔮', rarity: 'LEGENDARY', description: '바다의 신이라 불리는 전설.' },
  { id: 'l10', name: '칠색조', emoji: '🔥', rarity: 'LEGENDARY', description: '무지개색 날개를 가진 전설.' },
  { id: 'l11', name: '세레비', emoji: '🌿', rarity: 'LEGENDARY', description: '시간을 넘나드는 숲의 수호신.' },
  { id: 'l12', name: '레지락', emoji: '🪨', rarity: 'LEGENDARY', description: '바위로 된 전설의 거인.' },
  { id: 'l13', name: '레지아이스', emoji: '❄️', rarity: 'LEGENDARY', description: '얼음으로 된 전설의 거인.' },
  { id: 'l14', name: '레지스틸', emoji: '⚙️', rarity: 'LEGENDARY', description: '강철로 된 전설의 거인.' },
  { id: 'l15', name: '라티아스', emoji: '🐲', rarity: 'LEGENDARY', description: '마음이 통하는 전설의 용.' },
  { id: 'l16', name: '라티오스', emoji: '🐲', rarity: 'LEGENDARY', description: '제트기보다 빠른 전설의 용.' },
  { id: 'l17', name: '가이오가', emoji: '💧', rarity: 'LEGENDARY', description: '바다를 넓힌 전설의 포켓몬.' },
  { id: 'l18', name: '그란돈', emoji: '🔥', rarity: 'LEGENDARY', description: '대지를 넓힌 전설의 포켓몬.' },
  { id: 'l19', name: '레쿠쟈', emoji: '🐲', rarity: 'LEGENDARY', description: '오존층을 지배하는 천공의 용.' },
  { id: 'l20', name: '지라치', emoji: '⚙️', rarity: 'LEGENDARY', description: '천 년에 한 번 소원을 들어줍니다.' },
  { id: 'l21', name: '테오키스', emoji: '🔮', rarity: 'LEGENDARY', description: '우주 바이러스가 변이했습니다.' },
  { id: 'l22', name: '디아루가', emoji: '⚙️', rarity: 'LEGENDARY', description: '시간을 다스리는 신.' },
  { id: 'l23', name: '펄기아', emoji: '💧', rarity: 'LEGENDARY', description: '공간을 다스리는 신.' },
  { id: 'l24', name: '기라티나', emoji: '👻', rarity: 'LEGENDARY', description: '반전 세계의 주인.' },
  { id: 'l25', name: '크레세리아', emoji: '🔮', rarity: 'LEGENDARY', description: '아름다운 꿈을 꾸게 합니다.' },
  { id: 'l26', name: '다크라이', emoji: '🌑', rarity: 'LEGENDARY', description: '악몽을 보여주는 포켓몬.' },
  { id: 'l27', name: '아르세우스', emoji: '⚪', rarity: 'LEGENDARY', description: '우주를 창조한 신.' },
  { id: 'l28', name: '비크티니', emoji: '🔥', rarity: 'LEGENDARY', description: '승리를 가져다주는 포켓몬.' },
  { id: 'l29', name: '제크로무', emoji: '⚡', rarity: 'LEGENDARY', description: '이상을 추구하는 뇌격의 용.' },
  { id: 'l30', name: '레시라무', emoji: '🔥', rarity: 'LEGENDARY', description: '진실을 추구하는 백염의 용.' },
  { id: 'l31', name: '자시안', emoji: '✨', rarity: 'LEGENDARY', description: '검을 문 전설의 영웅.' },
  { id: 'l32', name: '자마젠타', emoji: '👊', rarity: 'LEGENDARY', description: '방패가 된 전설의 영웅.' },
  { id: 'l33', name: '미라이돈', emoji: '⚡', rarity: 'LEGENDARY', description: '미래에서 온 전설.' },
  { id: 'l34', name: '코라이돈', emoji: '👊', rarity: 'LEGENDARY', description: '과거에서 온 전설.' },
];

// 가챠 확률 로직 (확률 조정)
export const pullMonster = (): Monster => {
  const rand = Math.random();
  let tier: Rarity = 'COMMON';

  // 확률 설정: 전설 5%, 희귀 35%, 일반 60%
  if (rand > 0.95) tier = 'LEGENDARY'; 
  else if (rand > 0.60) tier = 'RARE'; 
  
  // 해당 티어의 몬스터 중 하나 랜덤 선택
  const pool = MONSTER_LIST.filter(m => m.rarity === tier);
  // 만약 풀이 비어있으면(그럴 리 없지만) 전체에서 선택
  if (pool.length === 0) return MONSTER_LIST[Math.floor(Math.random() * MONSTER_LIST.length)];
  
  return pool[Math.floor(Math.random() * pool.length)];
};